# -*- coding: utf-8 -*-
"""codigoBase_upd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLgLWjGzwZsk0dERCmEOc5T71xG61rHC
"""

import pandas as pd
import plotly.express as px
import streamlit as st 

# Carregando o dataset
df = pd.read_csv('https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv')

# Renomeando colunas de interesse
df = df.rename(columns={
    'newDeaths': 'Novos óbitos',
    'newCases': 'Novos casos',
    'deaths_per_100k_inhabitants': 'Óbitos por 100 mil habitantes',
    'totalCases_per_100k_inhabitants': 'Casos por 100 mil habitantes'
})

# Adicionando uma linha com o total geral
df_total = df.groupby('date').agg({
    'Novos óbitos': 'sum',
    'Novos casos': 'sum',
    'Óbitos por 100 mil habitantes': 'mean',
    'Casos por 100 mil habitantes': 'mean'
}).reset_index()
df_total['state'] = 'TOTAL'

# Concatenando o DataFrame total com o DataFrame original
df_combined = pd.concat([df, df_total], ignore_index=True)

# Selecionando os estados disponíveis, incluindo "TOTAL"
estados = list(df_combined['state'].unique())

# Usando multiselect com todos os estados selecionados por padrão, incluindo "TOTAL"
selected_states = st.sidebar.multiselect(
    'Selecione os estados:',
    options=estados,
    default=['TOTAL']  # Define "TOTAL" como selecionado por padrão
)

# Selecionando colunas de interesse
colunas = ['Novos óbitos', 'Novos casos', 'Óbitos por 100 mil habitantes', 'Casos por 100 mil habitantes']
column = st.sidebar.selectbox('Qual tipo de informação?', colunas)

# Filtrando os dados para os estados selecionados
df_filtered = df_combined[df_combined['state'].isin(selected_states)]

# Criando o gráfico
fig = px.line(df_filtered, x="date", y=column, color='state', title=f'{column} por Estado')
fig.update_layout(
    xaxis_title='Data', 
    yaxis_title=column.upper(), 
    title={'x':0.5}
)

# Exibindo o título e o gráfico na aplicação
st.title('DADOS COVID - BRASIL')
st.write('Nessa aplicação, o usuário tem a opção de escolher múltiplos estados e o tipo de informação para mostrar o gráfico. Utilize o menu lateral para alterar a mostragem.')
st.plotly_chart(fig, use_container_width=True)
st.caption('Os dados foram obtidos a partir do site: https://github.com/wcota/covid19br')
